### ISSUE TITLE
Do you want a logo?

### ISSUE THREAD

**Issue by meldra** [rmcan/swiftsky#17]
I'm thinking a swift shaped cloud or something like that.

**Comment by rmcan** [comment]
Hi, yes. Swift shaped cloud sounds good to me. Thank you.

**Comment by meldra** [comment]
Pick one (or none, and suggest changes) and I'll clean up a .svg for you:

![swiftskylogoprototype](https://user-images.githubusercontent.com/1224145/234940271-86bc70f5-c95f-4459-b01a-1ce327f0e6b7.png)
![swiftskylogoprototypedullrays](https://user-images.githubusercontent.com/1224145/234940276-03861f12-64f1-4156-b5ec-1515b178850a.png)
![swiftskylogoprototyperays](https://user-images.githubusercontent.com/1224145/234940277-56f96057-86e1-4986-997b-ad814673988e.png)
![swiftskylogoprototypesun](https://user-images.githubusercontent.com/1224145/234940286-ad52d4e6-0dee-4279-81b4-f69da4955281.png)

**Comment by meldra** [comment]
oop missed one

![swiftskylogoprototypecloud](https://user-images.githubusercontent.com/1224145/234946519-e5421b8d-514e-492a-8b48-da0d95207243.png)

**Comment by rmcan** [comment]
All of them look great. Can you create pull request by adding fifth one to images folder as logo.png? Also it would be great if you could make it rounded to match app icon style like in the following link. Thanks!

https://developer.apple.com/design/resources/#macos-apps
