### ISSUE TITLE
Hide like count

### ISSUE THREAD

**Issue by seboslaw** [rmcan/swiftsky#25]
Hey guys, great work on the client. I was wondering if you could consider an app setting that lets you hide the like and possibly reskeet count of posts. 
The background is digital mental health. Here's an article about the reasoning: https://www.wellandgood.com/hiding-likes-instagram-mental-health-benefits/

**Comment by rmcan** [comment]
Thanks for the suggestion. Added option to hide like and repost count in 212eb7801d4b26c9206a5765875c51148397ee00
