### ISSUE TITLE
Please reduce the restriction on minimum window width

### ISSUE THREAD

**Issue by srcshelton** [rmcan/swiftsky#27]
I'm used to having Social Media apps in narrow, tall windows at one side of a display.

However, the current release of swiftsky imposes a reasonably wide minimum window width.

If this could be reduced to about a quarter of the current value, this would be ideal!

**Comment by rmcan** [comment]
Minimum window width is reduced in 5b5973d82ed441793cfa225b92c39ebc9d3aa0dd
